
export const SEQUARE = {
	SET_CHESS: "SET_CHESS",
	CHANGE_VALUE: "CHANGE_VALUE",
	CHANGE_OWNER: "CHANGE_OWNER",
	CHANGE_LOCK: "CHANGE_LOCK",
	CREATE_SQUARES: "CREATE_SQUARES",
}

export const LIST = {
	ADD_LIST: "ADD_LIST",
	DEL_LIST: "DEL_LIST",
	CLEAR_LIST:"CLEAR_LIST",
}

export const INFO = {
	CHANGE_PLAYER: "CHANGE_PLAYER",
	CHANGE_GAMESTATE: "CHANGE_GAMESTATE",
	SET_ENDSTATE: "SET_ENDSTATE",
	SET_BEGINSTATE: "SET_BEGINSTATE",
}

export const STYLE = {
	SET_STYLE: "SET_STYLE",
	CREATE_STYLE: "CREATE_STYLE",
}